name: PR

on:
  pull_request:

jobs:
  base:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: bahmutov/npm-install@v1
      with:
        install-command: npm -g i renovate
        useLockFile: false

    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}

    - name: configure shell and git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        set -o pipefail

    - name: renovate dry run
      run: >
        npx -p renovate renovate
        --dry-run true
        --token ${{ secrets.RENOVATE_DRYRUN }}
        ${{ github.repository }}
        2>&1 | tee renovate-ci.dryrun.log
      env:
        LOG_LEVEL: debug
        RENOVATE_CONFIG_FILE: renovate-ci.js

    - name: commit log
      run: >
        git add -f renovate-ci.dryrun.log
        && git commit -m "ci: log (PR-${{ github.event.number }} / base)"
        && echo "logCommit=$(git rev-parse HEAD)" >>$GITHUB_ENV
        && git push -f origin HEAD:log

    output:
      logCommit: ${{ env.logCommit }}

  head:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: bahmutov/npm-install@v1
      with:
        install-command: npm -g i renovate
        useLockFile: false

    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}

    - name: configure shell and git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        set -o pipefail

    - name: renovate dry run
      run: >
        npx -p renovate renovate
        --dry-run true
        --token ${{ secrets.RENOVATE_DRYRUN }}
        ${{ github.repository }}
        2>&1 | tee renovate-ci.dryrun.log
      env:
        LOG_LEVEL: debug
        RENOVATE_CONFIG_FILE: renovate-ci.js

    - name: commit log
      run: >
        git add -f renovate-ci.dryrun.log
        && git commit -m "ci: log (PR-${{ github.event.number }} / head)"
        && echo "logCommit=$(git rev-parse HEAD)" >>$GITHUB_ENV
        && git push -f origin HEAD:log

    output:
      logCommit: ${{ env.logCommit }}

  log:
    needs:
      - base
      - head
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}

    - name: configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: add base log
      run: >
        git fetch origin ${{ needs.base.outputs.logCommit }}
        && git checkout ${{ needs.base.outputs.logCommit }} -- renovate-ci.dryrun.log
        && git add -f renovate-ci.dryrun.log
        && git commit -m "ci: log (PR-${{ github.event.number }} / base)"

    - name: add head log
      run: >
        git fetch origin ${{ needs.head.outputs.logCommit }}
        && git checkout ${{ needs.head.outputs.logCommit }} -- renovate-ci.dryrun.log
        && git add -f renovate-ci.dryrun.log
        && git commit -m "ci: log (PR-${{ github.event.number }} / head)"

    - name: push commits
      run: >
        echo "logCommit=$(git rev-parse HEAD)" >>$GITHUB_ENV
        && git push -f origin HEAD:log

    - name: Add comment linking to the log commit
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          The changes introduced when merging commit ${{ github.sha }}
          can be viewed [here](https://github.com/${{ github.repository }}/commit/${{ env.logCommit }}).
