name: Validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: bahmutov/npm-install@v1
        with:
          install-command: npm -g i renovate
          useLockFile: false

      - uses: actions/checkout@v2

      - name: validation
        run: npx renovate-config-validator
        env:
          LOG_LEVEL: debug
          RENOVATE_CONFIG_FILE: renovate-ci.js
