name: Validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/cache@v2
      path: ~./npm
      key: npm-renovate
    - name: install renovate
      run: npm -g i renovate

    - uses: actions/checkout@v2

    - name: validation
      run: npx renovate-config-validator
      env:
        LOG_LEVEL: debug
        RENOVATE_CONFIG_FILE: renovate-ci.js
